- hosts: all
  gather_facts: yes
  vars_files:
    - group_vars/all/vars.yml
  pre_tasks:
  - name: update packages
      dnf:
        update_cache: yes
        update_only: yes
      become: yes

  roles:
    - role: repos
      tags:
        - essential

    - role: petermosmans.customize-gnome
      vars:
        gnome_extension:
          - id: 1319
            enable: yes
          - id: 615
            enable: yes
          - id: 906
            enable: yes
      tags:
        - desktop


    - role: neofetch
      tags:
        - utility

    - role: gnome
      tags: 
        - desktop
