- hosts: all
  gather_facts: yes
  vars_files:
    - group_vars/all/vars.yml
  pre_tasks:
    - name: repos
      import_tasks: tasks/repos.yml
    - name: update packages
      dnf:
        update_cache: yes
        name: "*"
        state: latest
      become: yes

  roles:
    - role: petermosmans.customize-gnome
      vars:
        gnome_extensions:
          - id: 1319
            enable: yes
          - id: 615
            enable: yes
          - id: 906
            enable: yes
      tags:
        - desktop

    - role: zsh
      tags: utility

    - role: neofetch
      tags: utility

    - role: nvim
      tags: apps

    - role: apps
      tags: apps

    - role: gnome
      tags: desktop

    - role: celluloid
      tags: apps

- hosts: all
  tasks:
    - name: hostname
      import_tasks: tasks/hostname.yml
      tags: system
    - name: terminal
      import_tasks: tasks/terminal.yml
      tags: apps
    - name: radeon profile
      import_tasks: tasks/radeon.yml
      tags: apps
    - name: virt
      import_tasks: tasks/virt.yml
      tags: apps
