- hosts: all
  gather_facts: yes
  vats_files:
    - group_vars/all/vars.yml
  pre_tasks:
  - name: update packages
      dnf:
        update_cache: yes
        update_only: yes
      become: yes

  tasks:
    - include: tasks/repos.yml
    - include: tasks/gnome.yml

  roles:
    - role: jaredhocutt.gnome_extensions
      vars:
        gnome_extension_ids:
          - 1319
          - 615
          - 906
      tags:
        - desktop

    - role: neofetch
      tags:
        - utility

