--- 

- name: install gnome tools
  become: yes
  dnf:
    name: 
      - gnome-tweaks 
      - dconf 
      - python3-psutil 
      - openssl
    state: present

- name: setup wallpaper
  block:
    - name: copy wallpaper
      copy:
        src: files/wallpaper.jpg
        dest: /home/{{ username }}/.wallpaper.jpg
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - name: set wallpaper
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///home/{{ username }}/.wallpaper.jpg'"
    - name: set lockscreen
      dconf:
        key: "/org/gnome/desktop/screensaver/picture-uri"
        value: "'file:///home/{{ username }}/.wallpaper.jpg'"

- name: enable display scaling
  dconf:
    key: "/org/gnome/mutter/experimental-features"
    value: "['scale-monitor-framebuffer']"

- name: disable default super+n shortcut
  dconf:
    key: "/org/gnome/shell/keybindings/switch-to-application-{{ item }}"
    value: "['']"
  loop:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9

- name: show battery percentage
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percantage"
    value: "true"

- name: change default monospace font
  block:
    - name: install jetbrain mono
      become: yes
      dnf:
        name: jetbrains-mono-fonts
        state: present
    - name: set as deafult
      dconf:
        key: "/org/gnome/desktop/interface/monospace-font-name"
        value: "'JetBrains Mono 10'"

- name: switch to adwaita dark
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"


- name: enable tap to click
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: center new windows
  dconf:
    key: "/org/gnome/mutter/center-new-windows"
    value: "true"

- name: alt tab
  dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"

- name: switch workspace
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-{{ item }}"
    value: "['<Super>{{ item }}']"
  loop:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9

- name: move window
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-{{ item }}"
    value: "['<Super><Shift>{{ item }}']"
  loop:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9

- name: change alt+f4 to super+q
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/close"
    value: "['<Super>q']"

- name: change favourites
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['io.gitlab.librewolf-community.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'com.spotify.Client.desktop', 'com.discordapp.Discord.desktop']"

- name: toggle maximize
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/toggle-maximized"
    value: "['<Super>i']"

- name: maximize
  dconf: 
    key: "/org/gnome/desktop/wm/keybindings/maximize"
    value: "['<Super>k']"

- name: unmaximize
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/unmaximize"
    value: "['<Super>j']"

- name: tile-left
  dconf:
    key: "/org/gnome/mutter/keybindings/toggle-tiled-left"
    value: "['<Super>h']"

- name: tile-right
  dconf:
    key: "/org/gnome/mutter/keybindings/toggle-tiled-right"
    value: "['<Super>l']"

- name: move to workspace left
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
    value: "['<Shift><Super>h']"

- name: move to workspace rigt
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
    value: "['<Shift><Super>l']"

- name: fullscreen
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/toggle-fullscreen"
    value: "['<Super>o']"

- name: hide window
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/minimize"
    value: "['']"

- name: nautilus home
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    value: "['<Super>p']"

- name: screensaver disable key
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver"
    value: "['']"
