---

  - name: install fav apps via .rpm
    become: yes
    dnf:
      name: "{{ native_packages }}"
      state: present

  - name: yeet libreoffice
    become: yes
    dnf:
      name: "libreoffice*"
      autoremove: yes
      state: absent
    ignore_errors: true

  - name: install av apps via flatpaks
    flatpak:
      method: user
      name: "{{ flatpaks_packages }}"
      state: present
      remote: flathub
