---

  - name: Install neofetch
    become: yes
    dnf:
      name: "{{ neofetch_package }}"
      state: present

  - name: Copy config files
    copy:
      dest: /home/{{ username }}/.config
      group: "{{ username }}"
      mode: 0755
      owner: "{{ username }}"
      src: neofetch

  - name: Create alias
    lineinfile:
      path: /home/{{ username }}/.bashrc
      line: 'alias neofetch="neofetch --ascii /home/{{ username }}/.config/neofetch/art.asc"'
      state: present
